### Библиотека Numpy

##### Задание №1

In [1]:
import numpy as np
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [2]:
mean_a = np.array(np.mean(a, axis=0))
mean_a

array([2. , 8.4])

###### Задание №2

In [3]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание №3

In [4]:
y1 = np.array([-1, 0, 1, 1, -1])
y2 = np.array([-2.4, -0.4, 2.6, 1.6, -1.4])
a_centered_sp = y1 @ y2
a_centered_sp

8.0

In [5]:
print(a_centered_sp/4)

2.0


### Библиотека Pandas

#### Задание №1

In [13]:
import pandas as pd
author = pd.DataFrame({"author_id":[1, 2, 3],
                      "author_name": ["Тургенев", "Чехов", "Островский"]})
book = pd.DataFrame({"author_id":[1, 1, 1, 2, 2, 3, 3],
                    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    "price":[450, 300, 350, 500, 450, 370, 290]})

In [14]:
author

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [15]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

#### Задание №2

In [18]:
author_price = pd.merge(author, book, how = "right", on="author_id")
author_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

#### Задание №3

In [26]:
top_5 = author_price.nlargest(5, "price")
top_5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

#### Задание №4

In [36]:
author_stat = author_price.groupby("author_name").agg({"price": ["min", "max", "mean"]})
author_stat

price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000